# Конфигурация Cargo для Apple Silicon (M процессоры)
# Этот файл автоматически устанавливает правильные переменные окружения
# для компилятора C при сборке на архитектуре aarch64-apple-darwin

[env]
# Настройки компилятора C для Apple Silicon (M1, M2, M3, M4)
CC_aarch64-apple-darwin = "clang -Wno-int-conversion"

# Настройки компилятора C для Intel Mac (для кросс-компиляции)
CC_x86_64-apple-darwin = "clang -Wno-int-conversion"

# Дополнительные флаги компилятора для подавления предупреждений
CFLAGS_aarch64-apple-darwin = "-Wno-int-conversion"
CFLAGS_x86_64-apple-darwin = "-Wno-int-conversion"

# Настройки для сборки с GUI (webview)
[target.aarch64-apple-darwin]
rustflags = ["-C", "link-arg=-framework", "-C", "link-arg=Cocoa", "-C", "link-arg=-framework", "-C", "link-arg=WebKit"]

[target.x86_64-apple-darwin]
rustflags = ["-C", "link-arg=-framework", "-C", "link-arg=Cocoa", "-C", "link-arg=-framework", "-C", "link-arg=WebKit"]

# Настройки профиля сборки для оптимизации на Apple Silicon
[profile.release]
# Оптимизация для Apple Silicon
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"
strip = true

# Настройки для отладочной сборки
[profile.dev]
opt-level = 2
debug = true