[build]
#rustflags = ["-Ctarget-cpu=native", "-Clink-arg=-s"]
# or this: "-Ctarget-feature=+aes,+sha,+sse,+sse2,+avx,+avx2"

# Build these targets like this:
# Install docker
# cargo install cross
# cross build --release --no-default-features --target x86_64-unknown-linux-musl

[target.x86_64-unknown-linux-musl]
rustflags = ["-Ctarget-feature=+crt-static", "-Clink-arg=-s"]

[target.i686-unknown-linux-musl]
rustflags = ["-Ctarget-feature=+crt-static", "-Clink-arg=-s"]

[target.arm64-unknown-linux-musl]
rustflags = ["-Ctarget-feature=+crt-static", "-Clink-arg=-s"]

[target.armhf-unknown-linux-musl]
rustflags = ["-Ctarget-feature=+crt-static", "-Clink-arg=-s"]

[target.mips-unknown-linux-musl]
rustflags = ["-Ctarget-feature=+crt-static", "-Clink-arg=-s"]

[target.mipsel-unknown-linux-musl]
rustflags = ["-Ctarget-feature=+crt-static", "-Clink-arg=-s"]

[target.aarch64-apple-darwin]
rustflags = ["-Ctarget-cpu=native", "-Clink-arg=-s"]
# Suppress int-conversion warnings in webview-sys for Apple Silicon
cc = "clang -Wno-int-conversion"