[build]
#rustflags = ["-Ctarget-cpu=native", "-Clink-arg=-s"]
# or this: "-Ctarget-feature=+aes,+sha,+sse,+sse2,+avx,+avx2"

# Cargo configuration for Apple Silicon (M processors)
# This file automatically sets the correct environment variables
# for the C compiler when building on aarch64-apple-darwin architecture

[env]
# C compiler settings for Apple Silicon (M1, M2, M3, M4)
CC_aarch64-apple-darwin = "clang -Wno-int-conversion"

# C compiler settings for Intel Mac (for cross-compilation)
CC_x86_64-apple-darwin = "clang -Wno-int-conversion"

# Additional compiler flags to suppress warnings
CFLAGS_aarch64-apple-darwin = "-Wno-int-conversion"
CFLAGS_x86_64-apple-darwin = "-Wno-int-conversion"

# Settings for building with GUI (webview)
[target.aarch64-apple-darwin]
rustflags = ["-C", "link-arg=-framework", "-C", "link-arg=Cocoa", "-C", "link-arg=-framework", "-C", "link-arg=WebKit"]

[target.x86_64-apple-darwin]
rustflags = ["-C", "link-arg=-framework", "-C", "link-arg=Cocoa", "-C", "link-arg=-framework", "-C", "link-arg=WebKit"]

# Build profile settings for Apple Silicon optimization
[profile.release]
# Optimization for Apple Silicon
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"
strip = true

# Settings for debug build
[profile.dev]
opt-level = 2
debug = true