[build]
#rustflags = ["-Ctarget-cpu=native", "-Clink-arg=-s"]
# or this: "-Ctarget-feature=+aes,+sha,+sse,+sse2,+avx,+avx2"

# Build these targets like this:
# Install docker
# cargo install cross
# cross build --release --no-default-features --target x86_64-unknown-linux-musl

# Cargo configuration for Apple Silicon (M processors)
# This file automatically sets the correct environment variables
# for the C compiler when building on aarch64-apple-darwin architecture

[env]
# C compiler settings for Apple Silicon (M1, M2, M3, M4)
CC_aarch64-apple-darwin = "clang -Wno-int-conversion"

# C compiler settings for Intel Mac (for cross-compilation)
CC_x86_64-apple-darwin = "clang -Wno-int-conversion"

# Additional compiler flags to suppress warnings
CFLAGS_aarch64-apple-darwin = "-Wno-int-conversion"
CFLAGS_x86_64-apple-darwin = "-Wno-int-conversion"

# Settings for building with GUI (webview)
[target.aarch64-apple-darwin]
rustflags = ["-C", "link-arg=-framework", "-C", "link-arg=Cocoa", "-C", "link-arg=-framework", "-C", "link-arg=WebKit"]

[target.x86_64-apple-darwin]
rustflags = ["-C", "link-arg=-framework", "-C", "link-arg=Cocoa", "-C", "link-arg=-framework", "-C", "link-arg=WebKit"]

[target.x86_64-unknown-linux-musl]
rustflags = ["-Ctarget-feature=+crt-static", "-Clink-arg=-s"]

[target.i686-unknown-linux-musl]
rustflags = ["-Ctarget-feature=+crt-static", "-Clink-arg=-s"]

[target.mipsel-unknown-linux-musl]
rustflags = ["-Ctarget-feature=+crt-static", "-Clink-arg=-s"]